version: "3.9"
services:
  database:
  image: postgres
  environment:
    - POSTGRES_USER=<DB_USER>
    - POSTGRES_PASSWORD=<DB_PASSWORD>
    - POSTGRES_DB=drugstore
  volumes:
    - ./data:/var/lib/postgresql/data
