import Head from 'next/head'
import { Inter } from 'next/font/google'
import Main from './components/main'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Drugs Control</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='homeDiv'>
        <Main />
      </div>

      <style jsx>{`
      .homeDiv{
        width: 100vw;
        background-color: lightgray;
        display: flex;
        align-items: center;
        justify-content: center;
      }
      `}</style>
    </>
  )
}
